package com.streamflix.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.streamflix.dto.BillingDtos;
import com.streamflix.entity.*;
import com.streamflix.repository.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.util.LinkedMultiValueMap;
import org.springframework.util.MultiValueMap;
import org.springframework.web.client.RestClient;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.transaction.annotation.Transactional;
import java.time.Instant;
import java.util.List;

@Service
@Transactional
public class SubscriptionService {
    private final PlanRepository plans; private final SubscriptionRepository subscriptions; private final ProcessedWebhookEventRepository events; private final UserRepository users; private final ObjectMapper mapper; private final RestClient stripe; private final String secret; private final String webhookSecret; private final String frontendUrl;
    public SubscriptionService(PlanRepository plans, SubscriptionRepository subscriptions, ProcessedWebhookEventRepository events, UserRepository users, ObjectMapper mapper, @Value("${app.stripe.secret-key:}") String secret, @Value("${app.stripe.webhook-secret:}") String webhookSecret, @Value("${app.frontend-url:http://localhost:4200}") String frontendUrl) { this.plans = plans; this.subscriptions = subscriptions; this.events = events; this.users = users; this.mapper = mapper; this.secret = secret; this.webhookSecret = webhookSecret; this.frontendUrl = frontendUrl; this.stripe = RestClient.builder().baseUrl("https://api.stripe.com").build(); }
    public List<BillingDtos.PlanResponse> planList() { return plans.findAll().stream().map(this::plan).toList(); }
    public BillingDtos.SubscriptionResponse current(User user) { Subscription sub = subscriptions.findFirstByUserIdOrderByUpdatedAtDesc(user.getId()).orElse(null); if (sub == null) return free(); return response(sub); }
    public boolean hasPremium(User user) { Subscription sub = subscriptions.findFirstByUserIdOrderByUpdatedAtDesc(user.getId()).orElse(null); return sub != null && sub.getPlan().isPremium() && ("active".equals(sub.getStatus()) || "trialing".equals(sub.getStatus())); }
    public BillingDtos.CheckoutResponse checkout(User user, String planCode) { Plan plan = plans.findByCode(planCode).filter(Plan::isPremium).orElseThrow(() -> new ResponseStatusException(HttpStatus.BAD_REQUEST, "Choose a paid plan")); if (secret.isBlank() || plan.getStripePriceId() == null || plan.getStripePriceId().startsWith("price_replace")) throw new ResponseStatusException(HttpStatus.SERVICE_UNAVAILABLE, "Stripe test-mode keys and price IDs are not configured"); MultiValueMap<String,String> form = new LinkedMultiValueMap<>(); form.add("mode", "subscription"); form.add("line_items[0][price]", plan.getStripePriceId()); form.add("line_items[0][quantity]", "1"); form.add("success_url", frontendUrl + "/subscriptions?checkout=success"); form.add("cancel_url", frontendUrl + "/subscriptions?checkout=cancelled"); form.add("customer_email", user.getEmail()); form.add("client_reference_id", user.getId().toString()); form.add("metadata[user_id]", user.getId().toString()); form.add("metadata[plan_code]", plan.getCode()); try { JsonNode json = stripe.post().uri("/v1/checkout/sessions").headers(h -> h.setBearerAuth(secret)).contentType(MediaType.APPLICATION_FORM_URLENCODED).body(form).retrieve().body(JsonNode.class); return new BillingDtos.CheckoutResponse(json.get("url").asText()); } catch (Exception ex) { throw new ResponseStatusException(HttpStatus.BAD_GATEWAY, "Stripe checkout could not be created", ex); } }
    public void cancel(User user) { Subscription sub = subscriptions.findFirstByUserIdOrderByUpdatedAtDesc(user.getId()).orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "No subscription found")); if (sub.getStripeSubscriptionId() == null || secret.isBlank()) throw new ResponseStatusException(HttpStatus.CONFLICT, "No provider subscription is configured"); MultiValueMap<String,String> form = new LinkedMultiValueMap<>(); form.add("cancel_at_period_end", "true"); stripe.post().uri("/v1/subscriptions/" + sub.getStripeSubscriptionId()).headers(h -> h.setBearerAuth(secret)).contentType(MediaType.APPLICATION_FORM_URLENCODED).body(form).retrieve().toBodilessEntity(); }
    public void webhook(String payload, String signature) { if (webhookSecret.isBlank() || !StripeSignatureVerifier.verify(payload, signature, webhookSecret, 300)) throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Invalid Stripe webhook signature"); try { JsonNode event = mapper.readTree(payload); String eventId = event.path("id").asText(); if (eventId.isBlank() || events.existsByEventId(eventId)) return; handle(event.path("type").asText(), event.path("data").path("object")); events.save(new ProcessedWebhookEvent(eventId)); } catch (ResponseStatusException ex) { throw ex; } catch (Exception ex) { throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Invalid Stripe webhook payload", ex); } }
    private void handle(String type, JsonNode object) { if ("checkout.session.completed".equals(type)) { long userId = object.path("metadata").path("user_id").asLong(0); String planCode = object.path("metadata").path("plan_code").asText(); User user = users.findById(userId).orElse(null); Plan plan = plans.findByCode(planCode).orElse(null); if (user == null || plan == null) return; Subscription sub = subscriptions.findFirstByUserIdOrderByUpdatedAtDesc(user.getId()).orElseGet(() -> new Subscription(user, plan, "active")); sub.billing(text(object, "customer"), text(object, "subscription"), "active", null, false); subscriptions.save(sub); } else if (type.startsWith("customer.subscription.")) { String id = text(object, "id"); subscriptions.findByStripeSubscriptionId(id).ifPresent(sub -> { sub.billing(text(object, "customer"), id, text(object, "status"), epoch(object.path("current_period_end")), object.path("cancel_at_period_end").asBoolean(false)); subscriptions.save(sub); }); } else if ("invoice.paid".equals(type) || "invoice.payment_failed".equals(type)) { String id = text(object, "subscription"); subscriptions.findByStripeSubscriptionId(id).ifPresent(sub -> { sub.billing(sub.getStripeCustomerId(), id, "invoice.paid".equals(type) ? "active" : "past_due", sub.getCurrentPeriodEnd(), sub.isCancelAtPeriodEnd()); subscriptions.save(sub); }); } }
    private BillingDtos.PlanResponse plan(Plan p) { return new BillingDtos.PlanResponse(p.getCode(), p.getName(), p.getPriceCents(), p.getCurrency(), p.getBillingInterval(), p.isPremium()); }
    private BillingDtos.SubscriptionResponse response(Subscription s) { return new BillingDtos.SubscriptionResponse(s.getPlan().getCode(), s.getPlan().getName(), s.getStatus(), s.getCurrentPeriodEnd(), s.isCancelAtPeriodEnd(), hasPremium(s.getUser())); }
    private BillingDtos.SubscriptionResponse free() { Plan p = plans.findByCode("free").orElseThrow(); return new BillingDtos.SubscriptionResponse(p.getCode(), p.getName(), "free", null, false, false); }
    private String text(JsonNode node, String name) { return node.hasNonNull(name) ? node.get(name).asText() : null; }
    private Instant epoch(JsonNode node) { return node.isNumber() ? Instant.ofEpochSecond(node.asLong()) : null; }
}
