import { Component, inject } from '@angular/core';
import { AsyncPipe, CurrencyPipe, NgFor, NgIf } from '@angular/common';
import { catchError, forkJoin, of } from 'rxjs';
import { BillingService, Plan, SubscriptionStatus } from '../billing.service';
@Component({ selector: 'app-subscriptions', standalone: true, imports: [AsyncPipe, CurrencyPipe, NgFor, NgIf], template: `<main class="content-shell page-space"><p class="eyebrow">STREAMFLIX MEMBERSHIP</p><h1 class="page-title">Choose your plan</h1><ng-container *ngIf="data$ | async as data"><div class="subscription-status"><span>Current plan: <strong>{{ data.current.planName }}</strong></span><span class="status-badge">{{ data.current.status }}</span><button class="logout-link" *ngIf="data.current.premium && !data.current.cancelAtPeriodEnd" type="button" (click)="cancel()">Cancel renewal</button></div><div class="plan-grid"><article class="plan-card" *ngFor="let plan of data.plans" [class.featured-plan]="plan.code === 'premium'"><p class="eyebrow">{{ plan.code === 'premium' ? 'MOST POPULAR' : plan.code.toUpperCase() }}</p><h2>{{ plan.name }}</h2><p class="plan-price" *ngIf="plan.priceCents; else free">{{ plan.priceCents / 100 | currency:plan.currency:'symbol':'1.0-0' }}<small>/{{ plan.billingInterval }}</small></p><ng-template #free><p class="plan-price">Free</p></ng-template><ul><li>Curated movie catalogue</li><li>{{ plan.premium ? 'Premium HLS playback' : 'Browse and discover titles' }}</li><li>{{ plan.premium ? 'Continue watching and subtitles' : 'Create profiles and My List' }}</li></ul><button class="button button-primary full-width" *ngIf="plan.premium && data.current.planCode !== plan.code" type="button" (click)="checkout(plan.code)">Start with {{ plan.name }}</button><span class="plan-active" *ngIf="data.current.planCode === plan.code">Current plan</span></article></div><p class="form-error" *ngIf="error">{{ error }}</p></ng-container></main>` })
export class SubscriptionsComponent {
  private readonly billing = inject(BillingService); readonly data$ = forkJoin({ plans: this.billing.getPlans(), current: this.billing.getCurrent() }).pipe(catchError(() => of({ plans: [] as Plan[], current: { planCode: 'free', planName: 'Free', status: 'free', currentPeriodEnd: null, cancelAtPeriodEnd: false, premium: false } as SubscriptionStatus }))); error = '';
  checkout(code: string): void { this.billing.checkout(code).subscribe({ next: response => window.location.href = response.url, error: err => this.error = err.error?.detail ?? 'Stripe test mode is not configured yet.' }); }
  cancel(): void { this.billing.cancel().subscribe({ next: () => window.location.reload(), error: err => this.error = err.error?.detail ?? 'Could not cancel renewal.' }); }
}
