ALTER TABLE app_users ADD COLUMN role VARCHAR(20) NOT NULL DEFAULT 'USER';
ALTER TABLE movies ADD COLUMN published BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE series ADD COLUMN published BOOLEAN NOT NULL DEFAULT TRUE;
